services:
  postgres:
    container_name: dba_stackexchange
    image: chesskhaled/dba_stackexchange_img:latest
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s